<?php

namespace Ebay\Sell\Logistics\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * This complex type contains the request payload for the createFromShippingQuote
 * method.
 */
class CreateShipmentFromQuoteRequest extends AbstractModel
{
    /**
     * Supply a list of one or more shipping options that the seller wants to purchase
     * for this shipment. The baseShippingCost field that's associated with the
     * selected shipping rate is the cost of the base service offered in the rate. In
     * addition to the base service, sellers can add additional shipping services to
     * the base service. Shipping options include things such as shipping insurance or
     * a recipient's signature upon delivery. The cost of any added services is summed
     * with the base shipping cost to determine the final cost for the shipment. All
     * options added to the shipment must be chosen from the set of shipping options
     * offered with the selected rate.
     *
     * @var \Ebay\Sell\Logistics\Model\AdditionalOption[]
     */
    public $additionalOptions = null;

    /**
     * Optional text to be printed on the shipping label if the selected shipping
     * carrier supports custom messages on their labels.
     *
     * @var string
     */
    public $labelCustomMessage = null;

    /**
     * The seller's desired label size. Any supplied value is applied only if the
     * shipping carrier supports multiple label sizes, otherwise the carrier's default
     * label size is used. 4&quot;x6&quot;.
     *
     * @var string
     */
    public $labelSize = null;

    /**
     * The eBay-assigned ID of the shipping rate that the seller selected for the
     * shipment. This value is generated by a call to createShippingQuote and is
     * returned in the rates.rateId field.
     *
     * @var string
     */
    public $rateId = null;

    /**
     * The optional return address and contact details for the shipment. The return
     * address is printed on the shipping label. If not specified, the return address
     * defaults to the shipFrom address returned in shipping quote.
     *
     * @var \Ebay\Sell\Logistics\Model\Contact
     */
    public $returnTo = null;

    /**
     * The unique eBay-assigned ID of the shipping quote that was generated by a call
     * to createShippingQuote.
     *
     * @var string
     */
    public $shippingQuoteId = null;
}
